{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c91479d6",
   "metadata": {},
   "source": [
    "# Classifying pulmonary diseases with transfer learning"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "592491a5",
   "metadata": {},
   "source": [
    "<b>Contact info</b>\n",
    "<br>\n",
    "<b>Name:</b> Mardja Bueno, Ph.D.\n",
    "<br>\n",
    "<b>email:</b> mardja.bueno@gmail.com\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3595cc92",
   "metadata": {},
   "source": [
    "## 1. Overview and goals"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "90c07791",
   "metadata": {},
   "source": [
    "## 2. The dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d7cf1482",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "sns.set()\n",
    "from PIL import Image\n",
    "from pathlib import Path\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "149d12aa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of images in the training dataset :  6326\n",
      "Number of images in the testing dataset :  771\n",
      "Number of images in the validation dataset :  38\n"
     ]
    }
   ],
   "source": [
    "# create path for the folders where the training, test and validation images are\n",
    "train_folders = 'Chest X ray images/train/' \n",
    "test_folders = 'Chest X ray images/test/'\n",
    "val_folders = 'Chest X ray images/val/'\n",
    "\n",
    "# create empty lists for train, test and val\n",
    "total_train = {}\n",
    "total_test = {}\n",
    "total_val = {}\n",
    "\n",
    "# iterate through the length of the list\n",
    "for folder in os.listdir(train_folders):\n",
    "    if not folder.startswith('.'): # so it doesn't open the .DS Store folder on Mac\n",
    "        total_train[folder] = len(os.listdir(train_folders + folder))\n",
    "    \n",
    "for folder in os.listdir(test_folders):\n",
    "    if not folder.startswith('.'):\n",
    "        total_test[folder] = len(os.listdir(test_folders + folder))\n",
    "    \n",
    "for folder in os.listdir(val_folders):\n",
    "    if not folder.startswith('.'):\n",
    "        total_val[folder] = len(os.listdir(val_folders + folder))\n",
    "\n",
    "# sum the number of images in each list\n",
    "quantity_train = pd.DataFrame(list(total_train.items()), index = range(0,len(total_train)), columns = ['class','count'])\n",
    "quantity_test = pd.DataFrame(list(total_test.items()), index = range(0,len(total_test)), columns = ['class','count'])\n",
    "quantity_val = pd.DataFrame(list(total_val.items()), index = range(0,len(total_val)), columns = ['class','count'])\n",
    "\n",
    "# print how many images we have in each dataset\n",
    "print(\"Number of images in the training dataset : \", sum(total_train.values()))\n",
    "print(\"Number of images in the testing dataset : \",sum(total_test.values()))\n",
    "print(\"Number of images in the validation dataset : \",sum(total_val.values()))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c9fca197",
   "metadata": {},
   "source": [
    "The dataset is organized into 3 folders (train, test, val) and contains subfolders for each image category (Normal/Pneumonia/Covid-19/Tuberculosis). A total of 7135 x-ray images are present."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dbe92d4b",
   "metadata": {},
   "source": [
    "## 3. Exploratory data analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9c607203",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA4MAAAHwCAYAAAAcvrq8AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAABfu0lEQVR4nO3deViU9f7/8dfA4JK4YaAetb5qbkczFC0xg7QEXBC3sjA91cnM0lJzRczcl0iTTKtT51RWFiGhmaGW6cnU3CqlzFZXFHHHjW0+vz/8OUdERJRtuJ+P6/KSueeee973Am9e93zuG5sxxggAAAAAYCluxV0AAAAAAKDoEQYBAAAAwIIIgwAAAABgQYRBAAAAALAgwiAAAAAAWBBhEAAAAAAsiDBYCuzfv1+NGjXSJ598km3622+/rTFjxhTY+3To0EE7duwosOVdzenTp/XQQw+pS5cuWrlyZbbn1qxZo7lz5+Z7mePGjdP69euvOs+iRYv05ptv5nvZV7Jjxw49++yzBbIsK9i/f79atGhR3GXcsISEBPXr10+SNHfuXMXHxxdvQQDok/m0fft2vfDCC5IKvpeFhYXp1KlTBba80q4oj6nCcuzYMTVq1EiS9NVXX2nKlCnFXBEuZS/uAlAw3NzcNHPmTPn5+alevXrFXc4N27lzp44ePapVq1bleG7Hjh06efJkvpc5derUPOd5+OGH873c3Nx+++2Kjo4usOXB9Tz33HPFXQKA/48+ee1+//13JScnSyr4XrZkyZICWxZcz3333af77ruvuMvAJQiDpUS5cuX02GOPacSIEfroo49UpkyZbM+PGTNGDRo00D//+c8cjzt06KCuXbtq48aNOnnypJ544glt27ZNP/30k+x2uxYsWKDq1atLkj788EP98ssvSk9P12OPPabevXtLklavXq0FCxYoIyND5cqV0+jRo9WiRQu9+uqr+uGHH3T48GE1atRIUVFR2er68ssvNW/ePDkcDlWoUEFjx46Vp6enIiIilJycrLCwMH388ccqV66cJOnHH3/URx99pKysLFWsWFG33nqrYmNjde7cOXl6euqNN97Qiy++qD179ujEiROqUKGCoqKiVK9ePfXr1099+/ZVs2bN9OijjyowMFA//vijTp06pZEjR6pjx4569dVXdfz4cb3wwgvq0KGDevTooQ0bNujgwYMKCwvT0KFDJUlvvvmmYmNjVaFCBbVq1UpfffWVVq9enW3dvvvuO02ePFnLli3TmDFjVK5cOf366686evSoOnTooCpVqujrr79WSkqKpkyZIn9/f/3111+aNGmSzpw5o5SUFDVu3FivvPKKypYtq7Vr1yoqKkpubm5q0qSJ1q9frw8//FC1a9fWJ598okWLFsnhcKhKlSoaP3686tevry1btmjGjBlyOBySpIEDByo4ODhHnVFRUfrb3/6mP//8U+XKldOMGTNUv359paenKyoqSps3b1ZWVpb+/ve/KzIyUp6enurQoYOaN2+uXbt2afjw4erYsaNzma+++qr27NmjQ4cOOddj6tSpztfNnTtXt99+uyQ5H1etWjXb6/fu3avk5GSlpKSoadOmuuuuuxQfH6/9+/dr5MiR6tq1qzIyMjRjxgxt2LBB7u7uat68ufMYym3/ORwOTZs2TT/++KPOnDkjY4ymTJkiPz8/jRkzRidOnNC+ffsUEBCg2NhYxcTEqG7dupKkRx99VI888ojuv//+bNtw7ty5+uyzz1SlShXdeuutV/y+i46O1qpVq+Th4aGqVatq+vTp8vHx0R9//KGpU6fqxIkTysrKUr9+/dS7d++r1pnbfr3a/gKszqp9ctiwYfnqEc2bN1d0dLRSU1M1duxYde/ePVsv8/T01K5du3To0CE1atRIM2fOVIUKFa7aoy7VqFEjbdiwQWvWrNHKlSvlcDiUlJSk6tWr68EHH9T777+v3bt367HHHtPjjz+us2fP5trX9+zZo4iICJ08eVLe3t4yxqhbt27q2bOntm3bpqioKJ07d05ubm4aPHiw2rdvr5SUFI0ePVrHjx+XJAUGBjp7+6X+/ve/a8CAAfrmm2909uxZDR8+XEFBQZKU6/a8tIfce++9GjlypHN5V+u1Vzv2Ln397NmzVbNmTf31118qX768nnzySS1cuFB//fWXgoKCFBERIUn6+OOPtXDhQrm5uenmm2/W+PHjVbdu3avuv9jYWH388cfKyMjQyZMnNWDAAIWHhysuLi7b71l2u12dOnXSgw8+KEmaP3++Tpw44Xzvi1auXKk5c+aofPnyatasmXN6XFycVqxYoTfeeEMrV67UggULZLPZ5O7urlGjRql169ZKTU3V1KlT9euvvyojI0P+/v4aNWqU7HZ7rnVebb/mtr/w/xm4vH379hlfX1+TlZVl+vbta2bMmGGMMeatt94yo0ePNsYYM3r0aPPWW285X3Pp4/bt25tp06YZY4z5/PPPTePGjc3OnTuNMcY8/fTTZsGCBc75JkyYYIwx5tChQ8bf39/8+uuv5q+//jJdu3Y1x44dM8YY8+uvv5q7777bnDlzxkRHR5vg4GCTkZGRo+7ff//dtG3b1uzdu9cYY8z69evN3XffbVJTU83GjRtNly5drri+0dHRZuLEicYYYxYvXmxat25tUlNTjTHGfPHFF2by5MnOecePH28mTZpkjDHmkUceMV988YXZt2+fadiwoVm9erUxxpiEhARz77335lh2+/btndvy0KFD5vbbbzd79+41//3vf01wcLA5efKkcTgcZuzYsaZ9+/Y56rx0HUaPHm0eeOABk56ebg4fPmwaNmxo3nvvPWOMMe+884557LHHjDHGzJgxw8THxxtjjElPTzddu3Y1CQkJ5tixY+bOO+907pe4uDjTsGFDs2/fPvPdd9+Z8PBwc/bsWWOMMd98840JCQkxxhjTv39/s2zZMmOMMTt37jQvvvjiFets3Lix2bx5szHGmA8//ND06NHDGGPMq6++ambMmGEcDocxxpiXX37ZeQy0b9/ezJs3L9d9FBAQYFJSUkxWVpYZPny4c1u2b9/ebN++3TnvxccXj+OLr2/fvr05deqUOXfunGndurWZPn26McaYVatWmaCgIGOMMXPnzjWDBw826enpJisry4wZM8aMHz/+qvtv27ZtZsiQISYrK8sYY8wbb7xhBg4c6NxP//jHP5y1TZkyxcycOdMYY8yePXtMYGCgyczMzLauq1atMp07dzapqakmIyPDPPnkk+aRRx5xLu+tt94ySUlJpmXLliYtLc0YY8zbb79tVq1aZTIyMkznzp1NYmKiMcaYU6dOmU6dOpnvv//+qnXmtl+vtr8AK7Nyn7yeHrF48WLz5JNPGmNy9rI+ffqYtLQ0k56ebrp3725iY2Ov2qMu17BhQ3P06FGzePFi4+fnZ5KSkkxWVpbp3Lmz82fezp07ze23326ysrKu2tcffPBB88EHHzi31R133GEWL15sTpw4YYKCgpzvf+jQIRMQEGAOHDhg5s2b5+wTZ86cMUOHDjWnTp26Yp0X9+vOnTuNn5+fOXr06FW35+U95FJX67V5HXvbt283GzduNE2aNDE//fSTMcaYf/7zn859cfToUdO0aVNz6NAhs379enP//febo0ePOvdlp06djMPhyHX/nT592jz44IPO4/P777939uPLf89atWqV6dWrlzHGmKysLNO+fXvzxx9/ZFvXlJQU4+fnZ3777TdjjDGvv/66adiwoXN5F4+t++67z3z//ffO7fjqq68aY4wZM2aM83ekzMxMM2LECPPmm29etc7c9uvV9hcu4JPBUsTNzU0vvfSSunfvrnbt2uXrtRfPdtWpU0c333yzGjduLEm65ZZbsg01eeihhyRJ1atX19133+38RObw4cN69NFHnfPZbDbt3btXkuTr6yu7PeehtnHjRrVp00Z16tSRJPn7+8vLy0uJiYmy2WzXXHujRo2cn3yEhISoTp06Wrhwofbs2aNNmzZd8To0Dw8PBQYGSrpw9u/EiRNXXPbFoQzVq1dXtWrVdPLkSa1du1YhISGqVKmSJKlv377auHFjnnW2b99eHh4e8vb21k033aR77rlH0oVtfPH9R44cqW+//Vb/+te/tHv3bh0+fFhnz57Vli1bVL9+fed+6dGjh3PM/Zo1a7Rnzx7nvpGkU6dO6cSJE+rUqZMmTZqk1atXq23btho+fPgVa2vcuLFatWolSerVq5cmTZqk48ePa82aNUpNTXVea5mRkaFq1ao5X3fxNVcSEhKim2++WZLUu3dvTZs2TaNHj85zO13Utm1bVaxYUZLk4+Nzxe313//+V8OGDZOHh4ckqV+/fnrmmWecy7jS/mvRooUqV66sjz76SPv27dN3332nChUqOF/j5+fn/Do8PFyPPPKIhg0bpo8//li9e/eWu7t7tjo3bNigjh07Oo/BXr16aeHChdnmqV69uho3bqwePXooICBAAQEB8vf31++//669e/dmO6N6/vx5/fzzzwoPD8+1ztz2a177C7A6K/bJgugRl7rnnnucn6o2bNhQJ0+evGqPuprbb79dNWvWlCTVrl1b7dq1k5ubm+rUqaO0tDSdO3cu175+8uRJbd++Xe+//74kqX79+mrTpo0k6YcfflBKSkq2fmCz2bRr1y7dc889evLJJ3Xw4EG1bdtWzz//vLPXXO6RRx6RdKFHNmzYUJs3b9aPP/6Y6/aUsveQy+XWa69V7dq19fe//13SheOuYsWKKlOmjLy8vFShQgWdPHlS33zzjTp37iwvLy9JUs+ePTV16lTt379f0pX3X4UKFfT6669r7dq12r17t3755RedPXvW+b6X/p7Vvn17TZ06Vb/88ouSk5NVu3btHMOut27dqoYNG+q2226TJPXp00ezZ8/OsT5dunTR4MGDFRgYqLvvvlsDBgyQdOGY3bFjh2JjYyVd6IuSrlpnbvv1asd/lSpVrnnbl2aEwVKmZs2amjhxokaPHq3u3bs7p9tsNhljnI8zMjKyve7S4TIXf7G+Eje3/91zyOFwyG63KysrS/7+/nrllVeczx08eFA+Pj5atWqVbrrppisuy+Fw5GhmxhhlZmZetYbLXbr8Dz/8UDExMerbt69CQ0NVpUoV5w/AS3l4eDjX5WoNtWzZss6vL25Du92ebVteHg5yc/mQpCs1/uHDhysrK0udOnXSvffeq4MHD8oYI3d392zvKf1vXzgcDoWFhTmHozgcDh0+fFiVK1fWQw89pPbt2+vbb7/VN998o3nz5ikhISHbeuW2Du7u7nI4HIqIiHAG5zNnzigtLc05T2779vJlOhyObMfOpeuSnp5+xddfy/a6/BhyOBzZju0r7b81a9Zo6tSpeuyxx3TfffepXr16Wrp06RXXqW7dumrUqJG++uorLVu2TDExMVesNa/jwc3NTe+//7527NihDRs2aNq0abrnnnsUFhamihUrZruG5siRI84Glludue3XvPYXAOv1yevpEVdzcTiq9L9tdrUedTXX8nM+t75+8WftlX7+ZmVlqX79+tluGJScnCwvLy95eHjoq6++0oYNG7Rx40Y98MAD+te//pVtKOPly5MubLeLfTG37Slde1+8dFpex95F19oXL3fxmJGuvP8OHTqkPn366MEHH5Sfn59CQkL09ddfO+e7dJ3c3d3Vp08fxcbG6vDhw9lC1uXvebU6JWnYsGHq1auXvv32W8XFxenf//63YmNj5XA4NHfuXOdQzlOnTslms121zubNm19xv+a1v8DdREulkJAQBQQE6N1333VOq1q1qhITEyVd+IG4adOm61r2p59+KklKSkrShg0b5O/vL39/f3377bf6448/JElr165Vt27dnGdycuPv769169Zp3759kuS8tuuOO+646uvc3d2dP9Qut27dOvXo0UMPPPCA6tatq9WrVysrKyu/q3lVgYGBWrlypVJTUyXJeeaqIKxbt07PPPOMOnfuLOnCtR9ZWVlq2bKl8yyYJK1YscL5w7Fdu3b6/PPPdfjwYUkX7oj6j3/8Q9KF0LBz50717NlTkydP1qlTp5SSkpLjfX/55Rfnsj/++GO1aNFClSpVUrt27fTBBx8oPT1dDodD48ePv+LZvSv56quvlJqaKofDoZiYGLVv316SnGe1pQvXQFypnmt1zz33aNGiRcrIyJDD4dAHH3ygu++++6qv+fbbb9W+fXuFh4erWbNm+vLLL696jISHh2vWrFlq3ry585qgSwUEBCghIUGnTp2Sw+G44s0RfvnlF3Xt2lX169fXwIED9eijj2rHjh2qW7euypUr53zNwYMH1bVrVyUmJl61ztz2643sL8BKrNQnr6dHXK3PXsnVetSNyq2ve3p6qmXLloqLi5Mk7du3Txs2bJDNZpOvr6/27NmjzZs3S7pws53g4GAlJycrKipK8+fP1/33369x48bptttu02+//XbF9754N+iffvpJf/31l1q3bn3V7ZmX3HptQR170oW+uHz5ch07dkyStHjx4hzXs18uMTFRXl5eevrpp9WuXTtnwMqtNz7wwAP68ssv9dNPP2W7X8BFrVu31u+//+5c14v76FKZmZnq0KGDzp07p4cfflgTJkzQrl27lJ6ernbt2umdd96RMUbp6ekaNGiQ3n///avWmdt+vZH9ZRV8MlhKRUZGauvWrc7H/fr104gRIxQcHKzatWs7h1LkV1pamnr06KGMjAxFRkY6b6wxadIkDR8+3PnJ2YIFC7INvbuS2267TRMmTNDgwYOVlZWlcuXK6fXXX891uMZFbdq00YgRIzR58mQ1bdo023OPP/64XnjhBWdA8/X11a+//npd65obf39/Pfjgg+rTp4/KlSunBg0aqHz58gWy7GHDhumZZ57RTTfdJE9PT7Vu3Vp79+5VlSpVNHv2bI0ePVpubm5q1qyZ7Ha7ypcvr3bt2mnAgAF6/PHHZbPZ5OnpqXnz5slms2nEiBGaNm2aXnnlFdlsNg0ePDjHxfySdPPNN+uVV17RgQMH5OXlpVmzZkmSnn76ac2cOVM9evRQVlaWmjRpcs23Yb/55ps1YMAAHT9+XK1bt9ZTTz0lSRoxYoRefPFFffzxx2ratGmOfZgfgwYN0syZM9W9e3dlZmaqefPmGj9+/FVf89BDD+n5559XaGioMjMzdffddztvYnAl7du3V2RkZK5nPwMDA7Vr1y716tVLlSpVUuPGjXMM+2ncuLE6deqkXr166aabblK5cuUUGRmpMmXKaP78+Zo6dareeustZWZm6rnnnpOfn5+qVKmSa5257dcb2V+A1VilT44fPz7fPSIrK0uvvfaaBg8e7PxTOVdztR51o67W12fOnKlx48bpww8/VPXq1VW7dm2VK1dOXl5eio6O1qxZs5SWliZjjGbNmqXatWvrH//4h8aMGaOuXbuqTJkyatSokbp06XLF9962bZtiYmLkcDg0Z84cVa5c+ao9Ny+59dqCOvYk6e6779ajjz6qf/zjH3I4HPLy8tIbb7xx1U9q7777bsXGxiokJEQ2m0133nmnvLy8tGfPnivOX61aNTVr1kz169e/4ifUXl5eioqK0ogRI+Th4aHWrVvnmMdutysiIkIjRoyQ3W6XzWbTtGnTVKZMGY0bN05Tp05VaGioMjIy1LZtWz3xxBPKzMzMtc7c9muZMmWue39ZRlFeoAiUBtu3bzfvvvuu8/G///1v89xzzxXqe6amppqZM2c6L4BOTEw0d999t/NGITfiajchuF6X3rzA1W3bts107ty5QLY1AJRGhdmjrmb+/Pnm999/N8ZcuAHXvffe67xpyY26eKObglIYvba4HD161LRv394kJSUVdykoAHwyCORT3bp19a9//UsxMTGy2WyqWbOmJk+eXKjv6enpKQ8PD/Xu3Vt2u112u915JheFZ/To0dq0aZPmzJnDtgaAXBRXj/q///s/DRs2TG5ubsrKytKAAQOcNy1B4YiJidHs2bM1ZMgQ581/4Npsxlx2xS8AAAAAoNTjBjIAAAAAYEGEQQAAAACwIMIgAAAAAFhQqb+BzPHjZ+RwcFkkAJRmbm42Va169dv0Iyd6JACUbnn1x1IfBh0OQ6MDAOAK6JEAYG0MEwUAAAAACyIMAgAAAIAFFXoYnDlzpsaMGSNJWr9+vUJDQxUUFKQ5c+Y459m5c6d69uyp4OBgjRs3TpmZmZKkpKQk9e3bVyEhIRo0aJDOnDlT2OUCAAAAgCUUahjcsGGDPv30U0nS+fPnFRERofnz52v58uVKTEzU2rVrJUkjR47UCy+8oBUrVsgYo5iYGEnSxIkTFR4eroSEBDVr1kzz588vzHIBAAAAwDIKLQyeOHFCc+bM0VNPPSVJ2r59u2699VbVqVNHdrtdoaGhSkhI0IEDB3T+/Hn5+vpKknr27KmEhARlZGRo8+bNCg4OzjYdAIDS7kZG1QAAcK0K7W6iL7zwgoYNG6aDBw9Kkg4fPixvb2/n8z4+PkpOTs4x3dvbW8nJyTp+/Lg8PT1lt9uzTc+vatU8b3BNAAAoOhdH1dx7773OUTULFy5UzZo1NXDgQK1du1aBgYEaOXKkpkyZIl9fX0VERCgmJkbh4eHFXT4AwIUUShj85JNPVLNmTfn7+ysuLk6S5HA4ZLPZnPMYY2Sz2XKdfvH/S13++FocPXqa22YDQCnn5mYrFSf/Lh1V88svv2QbVSPJOarmtttuyzGqJjo6mjAIAMiXQgmDy5cvV0pKisLCwnTy5EmdPXtWBw4ckLu7u3OelJQU+fj4qEaNGkpJSXFOP3LkiHx8fOTl5aXU1FRlZWXJ3d3dOT8AAKXVjY6qAQAgPwolDP7nP/9xfh0XF6dNmzZp4sSJCgoK0p49e1S7dm0tW7ZMvXr1Uq1atVS2bFlt3bpVfn5+WrJkiQICAuTh4aFWrVpp+fLlCg0NVXx8vAICAgqjXAAAil1BjKrJr9LwaSoA4PoV2jWDlytbtqxmzJihIUOGKC0tTYGBgQoJCZEkRUVFKTIyUqdPn1bTpk3Vv39/SdKECRM0ZswYLViwQDVr1tTs2bOLqlwAAIpUQYyqyS8upQCA0i2vyyhsxphS3QVodABQ+pWWawYvunxUzXvvvafatWtr4MCB6tWrlzp16qSuXbtq4sSJ8vPz0/jx43XrrbfqiSeeyNf70CMBoHTLqz8W2SeDAAAgf65nVA0AANeKTwYBAC6vtH0yWFTokQBQuuXVHwvtj84DAAAAAEouwiAAAAAAWBBhEAAAAAAsiDAIAAAAABZEGAQAAAAAC+JPS6BYeVUuK/cyZYq7DJeRlZ6uYyfTirsMAEAhoz/mD/0RuD6EQRQr9zJldHjBqOIuw2X4DJoliWYHAKUd/TF/6I/A9WGYKAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFlSoYXDu3Lnq3LmzunTpov/85z+SpLFjxyooKEhhYWEKCwvTqlWrJEk7d+5Uz549FRwcrHHjxikzM1OSlJSUpL59+yokJESDBg3SmTNnCrNkAAAAALCEQguDmzZt0saNG7V06VItXrxYCxcu1J9//qnExES9//77WrJkiZYsWaKOHTtKkkaOHKkXXnhBK1askDFGMTExkqSJEycqPDxcCQkJatasmebPn19YJQMAAACAZRRaGLzzzjv13nvvyW636+jRo8rKylK5cuWUlJSkiIgIhYaGKjo6Wg6HQwcOHND58+fl6+srSerZs6cSEhKUkZGhzZs3Kzg4ONt0AABKo4IYUQMAwLWyF+bCPTw8FB0drX//+98KCQlRZmam2rRpowkTJqhixYoaOHCgYmNj1aBBA3l7eztf5+3treTkZB0/flyenp6y2+3ZpudHtWqeBbpOQHHz9q5Y3CUAKASXjqjJzMxU586dFRgY6BxR4+Pjk23+kSNHasqUKfL19VVERIRiYmIUHh5eTNUDAFxRoYZBSXr22Wc1YMAAPfXUU9qwYYNee+0153P9+vVTfHy86tevL5vN5pxujJHNZnP+f6nLH+fl6NHTcjjMja0ECg3BJv9SUlKLuwSgxHFzs7n8yb9LR9QkJyfnGFGTnJysjh07avDgwTp48GCOETXR0dGEQQBAvhTaMNE//vhDO3fulCSVL19eQUFBWr58uVasWOGcxxgju92uGjVqKCUlxTn9yJEj8vHxkZeXl1JTU5WVlSVJSklJyXFmFACA0uLiiJouXbrI39/fOaJm2rRpiomJ0ZYtWxQbG6vDhw9fcUQNAAD5UWifDO7fv1/R0dFatGiRJOmrr75S69atNW3aNLVp00Y33XSTPv74Y/Xo0UO1atVS2bJltXXrVvn5+WnJkiUKCAiQh4eHWrVqpeXLlys0NFTx8fEKCAgorJIBACh2NzKiJr9c/dNU4FKMNgLyr9DCYGBgoLZv367u3bvL3d1dQUFBGjx4sKpWraqHH35YmZmZCgoKUteuXSVJUVFRioyM1OnTp9W0aVP1799fkjRhwgSNGTNGCxYsUM2aNTV79uzCKhkAgGLzxx9/KD09XU2aNMk2oqZKlSrOG6nlNaImv7iUouQi2OQfl1EAOeV1GUWhXjM4ZMgQDRkyJNu0vn37qm/fvjnmbdy4sWJjY3NMr1WrlhYuXFhoNQIAUBIUxIgaAADyo9BvIAMAAPJWUCNqAAC4VjZjTKkeH8IQmJLN27uiDi8YVdxluAyfQbMYBgNcQWm4m2hxoEeWXPTH/KE/AleWV38stLuJAgAAAABKLsIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFhQoYbBuXPnqnPnzurSpYv+85//SJLWr1+v0NBQBQUFac6cOc55d+7cqZ49eyo4OFjjxo1TZmamJCkpKUl9+/ZVSEiIBg0apDNnzhRmyQAAAABgCYUWBjdt2qSNGzdq6dKlWrx4sRYuXKhffvlFERERmj9/vpYvX67ExEStXbtWkjRy5Ei98MILWrFihYwxiomJkSRNnDhR4eHhSkhIULNmzTR//vzCKhkAAAAALKPQwuCdd96p9957T3a7XUePHlVWVpZOnTqlW2+9VXXq1JHdbldoaKgSEhJ04MABnT9/Xr6+vpKknj17KiEhQRkZGdq8ebOCg4OzTQcAAAAA3JhCHSbq4eGh6OhodenSRf7+/jp8+LC8vb2dz/v4+Cg5OTnHdG9vbyUnJ+v48ePy9PSU3W7PNh0AgNKoIC6vAADgWtkL+w2effZZDRgwQE899ZR2794tm83mfM4YI5vNJofDccXpF/+/1OWP81KtmueNrQBQwnh7VyzuEgAUgksvr8jMzFTnzp3l7++viIgILVy4UDVr1tTAgQO1du1aBQYGauTIkZoyZYp8fX0VERGhmJgYhYeHF/dqAABcSKGFwT/++EPp6elq0qSJypcvr6CgICUkJMjd3d05T0pKinx8fFSjRg2lpKQ4px85ckQ+Pj7y8vJSamqqsrKy5O7u7pw/P44ePS2HwxTYeqFgEWzyLyUltbhLAEocNzeby5/8u/TyiuTk5ByXV0hyXl5x22235bi8Ijo6mjAIAMiXQguD+/fvV3R0tBYtWiRJ+uqrr/TQQw9p1qxZ2rNnj2rXrq1ly5apV69eqlWrlsqWLautW7fKz89PS5YsUUBAgDw8PNSqVSstX75coaGhio+PV0BAQGGVDABAsbp4ecW///1vhYSE5Pvyivxy9QANXIoTzED+FVoYDAwM1Pbt29W9e3e5u7srKChIXbp0kZeXl4YMGaK0tDQFBgYqJCREkhQVFaXIyEidPn1aTZs2Vf/+/SVJEyZM0JgxY7RgwQLVrFlTs2fPLqySAQAodjdyeUV+MXqm5CLY5B8jZ4Cc8ho5U6jXDA4ZMkRDhgzJNs3f319Lly7NMW/jxo0VGxubY3qtWrW0cOHCQqsRAICSoCAurwAAID8K9W6iAADg2uzfv1+RkZFKT09Xenq68/KKv/76S3v27FFWVpaWLVumgICAbJdXSHJeXgEAQH4U+t1EAQBA3grq8goAAK6VzRhTqi8W4HqIks3bu6IOLxhV3GW4DJ9Bs7gmAriC0nA30eJAjyy56I/5Q38Eriyv/sgwUQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFiQvTAXPm/ePH3xxReSpMDAQI0aNUpjx47V1q1bVb58eUnS4MGD1bFjR+3cuVPjxo3TmTNn1KpVK02cOFF2u11JSUkaOXKkjh49qrp16yoqKkoVKlQozLIBAAAAoNQrtE8G169fr3Xr1unTTz9VfHy8fvrpJ61atUqJiYl6//33tWTJEi1ZskQdO3aUJI0cOVIvvPCCVqxYIWOMYmJiJEkTJ05UeHi4EhIS1KxZM82fP7+wSgYAAAAAyyi0MOjt7a0xY8aoTJky8vDwUP369ZWUlKSkpCRFREQoNDRU0dHRcjgcOnDggM6fPy9fX19JUs+ePZWQkKCMjAxt3rxZwcHB2aYDAFAazZs3T126dFGXLl00a9YsSdLYsWMVFBSksLAwhYWFadWqVZKknTt3qmfPngoODta4ceOUmZlZnKUDAFxQoQ0TbdCggfPr3bt364svvtAHH3ygTZs2acKECapYsaIGDhyo2NhYNWjQQN7e3s75vb29lZycrOPHj8vT01N2uz3b9PyoVs2zYFYIKCG8vSsWdwkACsGlI2psNpueeOKJbCNqfHx8ss0/cuRITZkyRb6+voqIiFBMTIzCw8OLqXoAgCsq1GsGJem3337TwIEDNWrUKNWrV0+vvfaa87l+/fopPj5e9evXl81mc043xshmszn/v9Tlj/Ny9OhpORzmxlYChYZgk38pKanFXQJQ4ri52Vz+5N+lI2ok5RhRk5ycrI4dO2rw4ME6ePBgjhE10dHRhEEAQL4UahjcunWrnn32WUVERKhLly7atWuXdu/e7Rz2aYyR3W5XjRo1lJKS4nzdkSNH5OPjIy8vL6WmpiorK0vu7u5KSUnJcWYUAIDSoCBG1OSXqwdo4FKcYAbyL88weO7cOe3atUu+vr5atGiRduzYocGDB+tvf/vbVV938OBBPfPMM5ozZ478/f0lXQh/06ZNU5s2bXTTTTfp448/Vo8ePVSrVi2VLVtWW7dulZ+fn5YsWaKAgAB5eHioVatWWr58uUJDQxUfH6+AgICCWXMAAArJ9fZO6cZG1OQXo2dKLoJN/jFyBsgpr5Ezed5AZuzYsfrqq6+0fft2vfXWW6pZs6bGjx+f5xu//fbbSktL04wZM5wXvX///fd68skn9fDDD6tLly5q0qSJunbtKkmKiorS9OnTFRISorNnz6p///6SpAkTJigmJkadO3fWli1bNHTo0GtcdQAAisf19s6tW7fq0Ucf1fPPP68ePXpo165dWrFihfP5vEbUAACQH3l+Mrhv3z698sormjt3rnr06KHBgwerV69eeS44MjJSkZGRV3yub9++OaY1btxYsbGxOabXqlVLCxcuzPP9AAAoKa6ndxbEiBoAAPIjzzB48VbV69at0+jRo5WVlaWzZ88WemEAALiq6+mdl46oueihhx5yjqjJzMxUUFBQthE1kZGROn36tJo2beocUQMAwLXKMwy2aNFCnTt3lru7u1q2bKl//OMfatu2bVHUBgCAS7qe3llQI2oAALhWeYbB8ePH6/vvv1ejRo3k5uamf/7znwxFAQDgKuidAABXkOcNZNzd3XXkyBG99dZbOnfunE6fPi03tzxfBgCAZdE7AQCuIM/O9Oabb2rRokVKSEjQ+fPnNW/evGy3uQYAANnROwEAriDPMPj555/rX//6l8qXL6+qVasqJiZGy5YtK4raAABwSfROAIAryDMM2u12lSlTxvm4UqVKstvzvNQQAADLoncCAFxBnp2pZs2aWrNmjWw2m9LT0/X222+rVq1aRVEbAAAuid4JAHAF13Q30VGjRmnXrl3y9fXVHXfcoaioqKKoDQAAl0TvBAC4gjzDYPXq1fXuu+/q3LlzysrKkqenZ1HUBQCAy6J3AgBcQZ5hcOzYsdke22w2lS9fXg0aNNADDzwgd3f3QisOAABXRO8EALiCa/qjRz///LMaNWqkJk2a6Pfff1dSUpLWrVunadOmFXZ9AAC4JHonAKCky/OTwT/++EMffPCBc4jLAw88oMcff1wffvihunbtWugFAgDgauidAABXkGcYPHnyZLZrHcqVK6fTp0/LZrPJw8OjUIsDAMAV0TsB11W5SnmV8eBPweRHekamTp44V9xl4DrkeaT7+vpqxIgR6t27t4wxiouLU/PmzbV27VqVL1++KGoEAMCl0DsB11XGw675768r7jJcytOPtCvuEnCd8rxmcOLEiapZs6amT5+ul156SXXq1NELL7ygM2fOaNKkSUVRIwAALoXeCQBwBXl+MliuXDk9//zzev75553Tzp49q86dOxdqYQAAuCp6JwDAFeQZBr/88ktFR0fr7NmzMsbI4XDoxIkT+v7774uiPgAAXA69EwDgCvIMg7NmzdLQoUO1aNEiDRgwQF9++aUqVKhQFLUBAOCS6J0AAFeQ5zWD5cuXV+fOneXr66uyZcvqxRdf1Jo1a4qgNAAAXBO9EwDgCvIMg2XLllV6erpuueUW7dy5U25ubrLZbEVRGwAALoneCQBwBXkOE+3QoYOefPJJzZw5U3369NHWrVtVtWrVoqgNAACXRO8EALiCPMPgU089pW7duql69eqaP3++Nm/erK5duxZFbQAAuCR6JwDAFeQ5TFSSDh8+rLVr1yolJUX/93//p8TExMKuCwAAl0bvBACUdHl+Mjhs2DBt2bJFPj4+zmk2m02BgYGFWhgAAK6K3gkAcAV5hsHExER99dVXKlOmTFHUAwCAy6N3AgBcQZ7DROvVq6fMzMyiqAUAgFKB3gkAcAV5fjLYp08fdevWTS1atJDd/r/Zp0+fXqiFAQDgquidAABXkGcYfPXVV9WuXTvdcsstRVEPAAAuj94JAHAFeYZBNzc3vfjii0VQCgAApQO9EwDgCvK8ZrBp06Zas2ZNEZQCAEDpQO8EALiCPD8ZXL9+vWJiYuTh4SEPDw8ZY2Sz2bRt27aiqA8AAJdD7wQAuII8w+C7775bFHUAAFBq0DsBAK4g1zC4YcMG+fv766effrri87Vq1Sq0ogAAcEX0TgCAK8k1DH7++efy9/fXwoULczxns9kUFBRUqIUBAOBq6J0AAFeSaxicMmWKJF2xoQEAgJzonQAAV5Ln3UQBAAAAAKUPYRAAAAAALCjXMPjll19KktLT04usGAAAXBm9EwDgSnINg3PnzpUk9enTp8iKAQDAldE7AQCuJNcbyFSoUEHBwcFKTk5WaGhojuc/++yzQi0MAABXQ+8EALiSXMPgW2+9pZ07d2rcuHEaP358UdYEAIBLoncCAFxJrmHQ09NTrVu31htvvCEfHx/99NNPyszMVPPmzeXp6VmUNQIA4BLonQAAV5JrGLwoNTVV/fr1080336ysrCwlJyfr9ddfV8uWLYuiPgAAXA69EwDgCvIMgzNnzlRUVJTatGkjSdqwYYNmzJihmJiYPBc+b948ffHFF5KkwMBAjRo1SuvXr9f06dOVlpamTp06adiwYZLkHFZz5swZtWrVShMnTpTdbldSUpJGjhypo0ePqm7duoqKilKFChVuZJ0BAChUN9I7AQAoKnn+ncEzZ844m5kk+fv769y5c3kueP369Vq3bp0+/fRTxcfH66efftKyZcsUERGh+fPna/ny5UpMTNTatWslSSNHjtQLL7ygFStWyBjjbJgTJ05UeHi4EhIS1KxZM82fP/961xUAgCJxvb0TAICilGcYtNlsOnDggPPx/v375e7unueCvb29NWbMGJUpU0YeHh6qX7++du/erVtvvVV16tSR3W5XaGioEhISdODAAZ0/f16+vr6SpJ49eyohIUEZGRnavHmzgoODs00HAKAku97eOW/ePHXp0kVdunTRrFmzJF04uRoaGqqgoCDNmTPHOe/OnTvVs2dPBQcHa9y4ccrMzCz4FQEAlGp5DhN95pln1KdPH/n7+8tms2ndunWaMGFCngtu0KCB8+vdu3friy++0COPPCJvb2/ndB8fHyUnJ+vw4cPZpnt7eys5OVnHjx+Xp6en7HZ7tukAAJRk19M7Lx1RY7PZ9MQTT2jZsmWKiorSwoULVbNmTQ0cOFBr165VYGCgRo4cqSlTpsjX11cRERGKiYlReHh4Ea0hAKA0yDMM3n///apXr542btwoh8OhgQMHqn79+tf8Br/99psGDhyoUaNGyd3dXbt373Y+Z4yRzWaTw+GQzWbLMf3i/5e6/HFeqlXj7m0oXby9KxZ3CQDycD2989IRNZJyjKiR5BxRc9ttt+UYURMdHU0YBADkS55hUJLq1aunevXq5XvhW7du1bPPPquIiAh16dJFmzZtUkpKivP5lJQU+fj4qEaNGtmmHzlyRD4+PvLy8lJqaqqysrLk7u7unD8/jh49LYfD5Lt2FA2CTf6lpKQWdwlAiePmZitxJ//y2zsLYkRNfpW0bQbcCH6nKF5sf9d0TWHwehw8eFDPPPOM5syZI39/f0nSHXfcob/++kt79uxR7dq1tWzZMvXq1Uu1atVS2bJltXXrVvn5+WnJkiUKCAiQh4eHWrVqpeXLlys0NFTx8fEKCAgorJIBACh2NzKiJr84YVpy8Yt1/hXUyVK2/fXhZHXJlNfJ0kILg2+//bbS0tI0Y8YM57SHHnpIM2bM0JAhQ5SWlqbAwECFhIRIkqKiohQZGanTp0+radOm6t+/vyRpwoQJGjNmjBYsWKCaNWtq9uzZhVUyAADF6kZH1AAAkB95hsFRo0Y572iWH5GRkYqMjLzic0uXLs0xrXHjxoqNjc0xvVatWlq4cGG+3x8AgOJyPb2zIEbUAACQH3mGwZ07d1738BMAAKzoenpnQY2oAQDgWuUZBn18fNSlSxfdcccdqlChgnN6bp/6AQBgddfTOwtqRA0AANcqzzDYokULtWjRoihqAQCgVKB3AgBcQZ5hcPDgwTp//rz27NmjBg0aKC0tTeXLly+K2gAAcEn0TgCAK3DLa4Yff/xR999/vwYOHKjDhw/r3nvv1bZt24qiNgAAXBK9EwDgCvIMgzNnztQ777yjKlWqqEaNGpo1a5amTp1aFLUBAOCS6J0AAFeQZxg8f/68brvtNufjwMBAZWVlFWpRAAC4MnonAMAV5BkG7Xa7Tp486bw99p9//lnoRQEA4MronQAAV5DnDWQGDRqkRx55RCkpKRo+fLi+/fZbTZo0qShqAwDAJdE7AQCuIM8w2L59e9WrV0/ffvutHA6HnnnmGdWvX78oagMAwCXROwEAriDPYaKSlJmZKYfDIbvdLrs9z/wIAIDl0TsBACVdnmFw8eLF6t+/v3bs2KEtW7aob9++WrFiRVHUBgCAS6J3AgBcQZ6nKt955x19+umn8vHxkSQlJSVp4MCBCg4OLvTiAABwRfROAIAryPOTQQ8PD2czk6S//e1v8vDwKNSiAABwZfROAIAryPWTwZ9++kmS1KhRI02aNEl9+vSRu7u74uLi1LJlyyIrEAAAV0HvBAC4klzD4JAhQ7I9XrNmjfNrm82myMjIQisKAABXRO8EALiSXMPg6tWri7IOAABcHr0TAOBK8ryBTEpKij799FOdOHEi2/RRo0YVVk0AALg0eicAwBXkeQOZQYMGafv27TLGZPsHAACujN4JAHAFeX4ymJGRoXnz5hVFLQAAlAr0TgCAK8jzk8GmTZvq119/LYpaAAAoFeidAABXkOcngy1btlT37t3l7e0tu/1/s3/11VeFWhgAAK6K3gkAcAV5hsG3335bUVFRuuWWW4qiHgAAXB69EwDgCvIMg5UqVVLnzp2LohYAAEoFeicAwBXkGQbbtGmjmTNnKigoSGXKlHFOb9q0aaEWBgCAq6J3AgBcQZ5h8LPPPpMkrVixwjnNZrNx3QMAALmgdwIAXEGeYXD16tVFUQcAAKUGvRMA4AryDIP/+c9/rjj9scceK/BiAAAoDeidAABXkGcYvPTvJKWnp2vz5s3y9/cv1KIAAHBl9E4AgCvIMwxOnz492+Pk5GSNGzeu0AoCAMDV0TsBAK7ALb8vqF69ug4cOFAYtQAAUCrROwEAJVG+rhk0xigxMVHVqlUr1KIAAHBl9E4AgCvI1zWDklSzZk2NGjWq0AoCAMDV0TsBAK4g39cMAgCAq6N3AgBcQa5hcOzYsbm+yGazadq0aYVSEAAAroreCQBwJbmGwQYNGuSYdvz4cb377ruqVatWoRYFAIAroncCAFxJrmHw8ccfz/Z4/fr1Gj16tEJDQxUZGVnohQEA4GronQAAV5LnNYOZmZl6+eWX9emnn2rixIkKDg4uiroAAHBZ9E4AgCu4ahjcvXu3hg8frgoVKig+Pl41atQoqroAAHBJ9E4AgKvI9Y/OL168WA8++KA6duyohQsX0swAAMgDvRMA4Epy/WRw3LhxcnNz05tvvql//etfzunGGNlsNm3btq1ICgQAwFXQOwEAriTXMPjVV18VZR0AALg8eicAwJXkGga5BTYAAPlD7wQAuJJcrxkEAAAAAJRehEEAAAAAsKBCDYOnT59W165dtX//fknS2LFjFRQUpLCwMIWFhWnVqlWSpJ07d6pnz54KDg7WuHHjlJmZKUlKSkpS3759FRISokGDBunMmTOFWS4AAAAAWEahhcEff/xRDz/8sHbv3u2clpiYqPfff19LlizRkiVL1LFjR0nSyJEj9cILL2jFihUyxigmJkaSNHHiRIWHhyshIUHNmjXT/PnzC6tcAABKhBs9kQoAwLUqtDAYExOjCRMmyMfHR5J07tw5JSUlKSIiQqGhoYqOjpbD4dCBAwd0/vx5+fr6SpJ69uyphIQEZWRkaPPmzQoODs42HQCA0qogTqQCAHCtcr2b6I2aOnVqtsdHjhxRmzZtNGHCBFWsWFEDBw5UbGysGjRoIG9vb+d83t7eSk5O1vHjx+Xp6Sm73Z5ten5Vq+Z5YysClDDe3hWLuwQAheTiidRRo0ZJyn4iNTk5WR07dtTgwYN18ODBHCdSo6OjFR4eXozVAwBcTaGFwcvVqVNHr732mvNxv379FB8fr/r168tmszmnX/zDvBf/v9Tlj6/F0aOn5XCY6y8chYpgk38pKanFXQJQ4ri52UrFyb8bPZGaX6VhmwEX8TtF8WL7u6YiC4O7du3S7t27ncM+jTGy2+2qUaOGUlJSnPMdOXJEPj4+8vLyUmpqqrKysuTu7q6UlBTnkFMAAKwgvydS84sTpiUXv1jnX0GdLGXbXx9OVpdMeZ0sLbI/LWGM0bRp03Ty5EllZGTo448/VseOHVWrVi2VLVtWW7dulSQtWbJEAQEB8vDwUKtWrbR8+XJJUnx8vAICAoqqXAAAit2uXbu0YsUK5+O8TqQCAJAfRRYGGzdurCeffFIPP/ywunTpoiZNmqhr166SpKioKE2fPl0hISE6e/as+vfvL0maMGGCYmJi1LlzZ23ZskVDhw4tqnIBACh2+T2RCgBAfhT6MNHVq1c7v+7bt6/69u2bY57GjRsrNjY2x/RatWpp4cKFhVofAAAl1aUnUjMzMxUUFJTtRGpkZKROnz6tpk2bOk+kAgBwrYrsmkEAAHBtbuREKgAA16rIhokCAAAAAEoOwiAAAAAAWBBhEAAAAAAsiDAIAAAAABZEGAQAAAAACyIMAgAAAIAFEQYBAAAAwIIIgwAAAABgQYRBAAAAALAgwiAAAAAAWJC9uAsAUDwqVymvMh78CLhW6RmZOnniXHGXAQAAUGD4TRCwqDIeds1/f11xl+Eynn6kXXGXAAAAUKAYJgoAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBB9uIuAAAAlEyVqpRTWQ+P4i7DZaRlZOjUifPFXQYAXDPCIAAAuKKyHh56/ov3irsMl/Fyp/6SCIMAXEehDhM9ffq0unbtqv3790uS1q9fr9DQUAUFBWnOnDnO+Xbu3KmePXsqODhY48aNU2ZmpiQpKSlJffv2VUhIiAYNGqQzZ84UZrkAAAAAYBmFFgZ//PFHPfzww9q9e7ck6fz584qIiND8+fO1fPlyJSYmau3atZKkkSNH6oUXXtCKFStkjFFMTIwkaeLEiQoPD1dCQoKaNWum+fPnF1a5AACUCDd6IhUAgGtVaGEwJiZGEyZMkI+PjyRp+/btuvXWW1WnTh3Z7XaFhoYqISFBBw4c0Pnz5+Xr6ytJ6tmzpxISEpSRkaHNmzcrODg423QAAEqrgjiRCgDAtSq0awanTp2a7fHhw4fl7e3tfOzj46Pk5OQc0729vZWcnKzjx4/L09NTdrs92/T8qlbN8zrXACiZvL0rFncJlsW2R2G7eCJ11KhRkrKfSJXkPJF622235TiRGh0drfDw8OIqHQDggorsBjIOh0M2m8352Bgjm82W6/SL/1/q8sfX4ujR03I4zPUXjkLFL9f5l5KSWiDLYdvnX0FtexQ8NzdbqTj5d6MnUvOrNGyzkoafrcWHbV+82P6uqcjCYI0aNZSSkuJ8nJKSIh8fnxzTjxw5Ih8fH3l5eSk1NVVZWVlyd3d3zg8AgFXk90RqfuV1wpRf7vKPE3bFh21fvDhhWjLldbK0yP7o/B133KG//vpLe/bsUVZWlpYtW6aAgADVqlVLZcuW1datWyVJS5YsUUBAgDw8PNSqVSstX75ckhQfH6+AgICiKhcAgGKX3xOpAADkR5GFwbJly2rGjBkaMmSIOnfurHr16ikkJESSFBUVpenTpyskJERnz55V//79JUkTJkxQTEyMOnfurC1btmjo0KFFVS4AAMUuvydSAQDIj0IfJrp69Wrn1/7+/lq6dGmOeRo3bqzY2Ngc02vVqqWFCxcWan0AAJRUl55ITUtLU2BgYLYTqZGRkTp9+rSaNm3qPJEKAMC1KrJrBgEAwLW5kROpAABcqyIbJgoAAAAAKDkIgwAAAABgQYRBAAAAALAgwiAAAAAAWBBhEAAAAAAsiDAIAAAAABZEGAQAAAAACyIMAgAAAIAFEQYBAAAAwIIIgwAAAABgQYRBAAAAALAgwiAAAAAAWBBhEAAAAAAsiDAIAAAAABZEGAQAAAAACyIMAgAAAIAFEQYBAAAAwIIIgwAAAABgQYRBAAAAALAgwiAAAAAAWBBhEAAAAAAsiDAIAAAAABZEGAQAAAAACyIMAgAAAIAFEQYBAAAAwIIIgwAAAABgQYRBAAAAALAgwiAAAAAAWBBhEAAAAAAsiDAIAAAAABZEGAQAAAAAC7IXdwEAYDVVK5eXvQw/fq9VZnqmjp88V9xlAABQ6vDbCAAUMXsZu35fsLa4y3AZtw0KLO4SAAAolRgmCgAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFgQYRAAAAAALIgwCAAAAAAWRBgEAAAAAAsiDAIAAACABdmL40379eunY8eOyW6/8PaTJk3SmTNnNH36dKWlpalTp04aNmyYJGnnzp0aN26czpw5o1atWmnixInO1wEAYAX56ZsAAFyrIk9Vxhjt3r1bX3/9tbOpnT9/XiEhIVq4cKFq1qypgQMHau3atQoMDNTIkSM1ZcoU+fr6KiIiQjExMQoPDy/qsgEAKBb57ZsAAFyrIh8m+ueff0qSHn/8cXXr1k3vv/++tm/frltvvVV16tSR3W5XaGioEhISdODAAZ0/f16+vr6SpJ49eyohIaGoSwYAoNjkp28CAJAfRf7J4KlTp+Tv76/x48crIyND/fv31xNPPCFvb2/nPD4+PkpOTtbhw4ezTff29lZycnK+3q9aNc8Cqx0oCby9KxZ3CZbFti8+Vt72+emb+UWPLHhWPlaLG9u+eLH9XVORh8EWLVqoRYsWzse9e/dWdHS0/Pz8nNOMMbLZbHI4HLLZbDmm58fRo6flcJgbLxyFgh8c+ZeSklogy2Hb5x/bvvjkte3d3GylNtjkp2/mV149kmM1//g5UXzY9sWroLY/ClZe/bHIh4lu2bJFGzZscD42xqhWrVpKSUlxTktJSZGPj49q1KiRbfqRI0fk4+NTpPUCAFCc8tM3AQDIjyIPg6mpqZo1a5bS0tJ0+vRpffrppxo+fLj++usv7dmzR1lZWVq2bJkCAgJUq1YtlS1bVlu3bpUkLVmyRAEBAUVdMgAAxSY/fRMAgPwo8mGi7du3148//qju3bvL4XAoPDxcLVq00IwZMzRkyBClpaUpMDBQISEhkqSoqChFRkbq9OnTatq0qfr371/gNVWqUk5lPTwKfLmlVVpGhk6dOF/cZQCAJeS3bwIAcK2K5Q/2DR06VEOHDs02zd/fX0uXLs0xb+PGjRUbG1uo9ZT18NDzX7xXqO9Rmrzcqb8kwiAAFJX89E0AAK5VkQ8TBQAAAAAUP8IgAAAAAFgQYRAAAAAALIgwCAAAAAAWVCw3kAEAAACAy1WtXF72MkSUa5WZnqnjJ89d9+vZ0gAAAABKBHsZu35fsLa4y3AZtw0KvKHXM0wUAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBhEEAAAAAsCDCIAAAAABYEGEQAAAAACyIMAgAAAAAFkQYBAAAAAALIgwCAAAAgAURBgEAAADAggiDAAAAAGBBLhEGP/vsM3Xu3FlBQUH64IMPirscAABKDHokAOB62Yu7gLwkJydrzpw5iouLU5kyZfTQQw/prrvu0m233VbcpQEAUKzokQCAG1Hiw+D69evVpk0bValSRZIUHByshIQEDR48+Jpe7+Zmu6b5qpavcL0lWtK1btdrWlbFqgW2LCsoyG1fsULZAluWFRTktrdXZNvnR17bviD3jSspih5Jf8wf+mPxoT8WL3pk8bnats9rv9iMMaagCypIb7zxhs6ePathw4ZJkj755BNt375dkydPLubKAAAoXvRIAMCNKPHXDDocDtls/0u0xphsjwEAsCp6JADgRpT4MFijRg2lpKQ4H6ekpMjHx6cYKwIAoGSgRwIAbkSJD4Nt27bVhg0bdOzYMZ07d04rV65UQEBAcZcFAECxo0cCAG5Eib+BTPXq1TVs2DD1799fGRkZ6t27t5o3b17cZQEAUOzokQCAG1HibyADAAAAACh4JX6YKAAAAACg4BEGAQAAAMCCCIMAAAAAYEGEQQAAAACwIMIgAAAAAFhQif/TEq7g9OnTevnll7V582a5u7urUqVKGjNmjJo2baozZ84oKipK69atU/ny5eXp6akhQ4bI399f69ev16RJk5SQkJBtefPmzVNqaqr69eun/v37a/Xq1fruu+/01FNP6ZZbbpExRmlpaQoMDNRzzz2nChUqOF+bnJysXr16ad26dc5pb775phYvXqwyZcqoc+fOGjRoUJFtm+uxf/9+hYSEqH79+rLZbMrIyJCPj4+mT5+ukSNHqnr16oqKinLO/+qrr0qShgwZon79+unQoUO66aabnM/ffPPNevvtt7PNd1FcXJw2bdqkGTNmaMyYMYqPj9fatWtVvXp15zxPP/20fvnlF61evVqStHv3bs2cOVO///67ypYtq7p162rUqFGqU6eOJKlDhw4KDQ3VsGHDnMsYM2aM7rzzTvXs2VP9+vXT4MGDddddd0mSMjMzde+99yo4OFjjx48v6M1ZKPbv36/77rtP//73v3X33Xc7p3fo0EHvvfeeqlatmutxL13YHhs3blTlypUlSefOnVOVKlU0ffp01a9f/5r3hSQtXLhQM2fO1Ndffy1vb29nfRe/d4rDxIkTtW3bNmVkZGjv3r2qX7++JKl///7avHmzZsyY4Zz3u+++07x587Rw4UK9+uqr+uijj3TzzTdLktLT02W32/Xiiy/Kz88v23ZzOBwqV66cJk+erMaNG2f7vrnUgw8+qL59+6pDhw4qV66cPDw8JEmpqalq1qyZZsyYoZtuuknGGL3zzjuKj4+XJLm5uemJJ55Qly5dJP1v39auXdu57IvHcq1atXLd3hkZGZo3b56++OILlS1bVmXLltXjjz+uzp07O9dx+vTp2rx5s2w2mypVqqTRo0c7/zxCo0aNtGvXLklSQkKC3nzzTWVmZsoYo7CwMD3xxBM3vL9QeOiPBY8eWfLRI3NHf/yfktIfCYM3yOFwaMCAAbrrrrsUHx8vu92ujRs3asCAAfr888/17LPPqkmTJvr8889VpkwZ/fzzz3ryySf18ssvy9/fX+np6UpMTFSzZs2cy1y6dKnmzZuX472aNWumhQsXSrpwAEVEROjFF1/USy+9JElau3atpk2bppSUFOdr1q9fr88++0yLFy9W+fLl9cwzz2jlypUKCgoq5C1zY3x8fLRkyRLn4xkzZmjWrFmSLhzwISEhuv/++6/42ilTpjibSH5Vr15dK1euVL9+/SRd+EXm559/lpvbhQ/Rjxw5ov79+2vEiBHq1q2bJGnJkiV6+OGHtXTpUnl5eUmS3n33XXXs2DHbfs3N2rVrdfvtt+uLL77QiBEjVL58+euqvah5eHho/PjxWrp0qTw9PZ3TjTF66qmncj3uL+6bZ599Vj179nS+burUqXr11Vf1yiuvSMp7X1wUFxen++67T4sXL9ZTTz1VyGt9bSZMmCDpfw334rEcFxeX52sfeuihbL+MvfPOO5oxY4Y++eQTSdm325dffqnIyEjFxsZKyvl9c7k333zT2azS09MVHh6u+Ph4hYeHa86cOfr555/1/vvvq2LFijp06JAeeeQRVa1aVW3btr2OrXDB+PHjlZaWpri4OHl6emrfvn0aMGCA0tPT1b17d73zzjtyOBz67LPPZLPZtHXrVj399NP6+uuvnY1ZuvCL/MyZMxUXF6eqVavqzJkz6tevn+rWrav77rvvuutD4aE/Fh56ZMlHj7wy+uP/lJT+yDDRG/Tdd9/p4MGDevbZZ2W3X8jWbdq00fTp07VhwwYlJSVp7NixKlOmjCTp73//uwYNGqT58+fLZrOpe/fuWrZsmXN527ZtU+XKldWwYcOrvq+Hh4dGjRql5cuX69SpU5Kk2NhY55m9i37++We1a9dOnp6ecnd31z333KMvv/yyIDdBkbjrrrv022+/SZIGDRqkiRMn6sSJEwX+PkFBQVqxYoXz8Zdffql7773X+XjRokVq27ats8lJUlhYmPz8/LRo0SLntIEDB2rs2LFKT0/P8z3j4uLUsWNHNW/eXJ9//nnBrEgR8PHxUdu2bTVz5sxs0zdv3nzV4/5K0tPTlZKS4jwLKuW9LyTpl19+0cmTJzVgwADFxMTI4XAU0NqVDA6HQ4cOHcq2XS6VmprqPEuaX6mpqUpNTVWVKlV05swZvfvuuxo/frwqVqwoSapRo4Zmz57tPJN8Pfbt26cVK1Zo6tSpzl+G6tSpo7Fjxzp/oT9y5IgyMjKUkZEhSfLz89O0adNy7Mvjx48rIyND58+flyRVqFBBM2bM0G233Xbd9aFw0R+LDj2y5KFHFi764//caH8kDN6gn3/+WY0bN85xJiYwMFBJSUlq1qyZbDZbtudat26tHTt2SJJ69uypL774wrlj4+Pj1bt372t6b29vb1WqVEm7d++WdGEoyOVNsmnTplq3bp1OnDihtLQ0rV69WkeOHLmeVS02GRkZWrFihXx9fSVJrVq1UkhIiKZMmXLF+SMjIxUWFub8t2DBgmt+ryZNmujo0aPObfTFF1+oU6dOzud37Nih22+/PcfrLt2nkhQaGqo6derotddeu+r7HTt2TOvXr9d9992nTp066eOPP77mWkuCMWPGaN26dfr222+d044dO5bncS9J0dHR6tatmwICAtSlSxfVrFlTI0eOdD6f176QpMWLFyskJETNmjWT3W7XN998UxirWaQ++ugjhYWFqX379mrfvr3OnTunadOmOZ+Pjo5WWFiYgoKCNH78ePXt29f53OHDh7Md+2FhYc4hJJL05JNPKjQ0VG3bttWAAQP0yCOPqFOnTvrzzz9lt9t16623ZqulefPmatCgwXWvS2JiourXr59tSJp04Xt43759OnHihPr3768ff/xR/v7+GjRokN577z21aNFCZcuWzfaaxo0b67777tP999+v3r1766WXXpLD4chRM0oO+mPRoEeWXPTIgkV/LJz+SBi8QW5ubjl2ykU2m01ZWVk5pmdkZDh/CNSuXVu33nqrNm3apPT0dK1Zs8Y5Bvla2Gy2XN9fkvz9/Z1j8J944gn5+fll+2i5pLr0m7Zbt24yxuj55593Pj98+HBt3779imdxp0yZoiVLljj/XbwG5PIfvNKF4RqXTw8KCtLKlSt18uRJnT59WrVq1XI+dy379KKJEyfqk08+UWJiYq7ruXTpUrVp00aVK1fWfffdp127dunnn3/Odf6SxtPTU5MnT9b48eN1+vRpSde+jZ599lktXbpU77zzjjIyMnTPPfdkG0ojXX1fZGRk6LPPPlPXrl0lSZ06ddJHH31UGKtZYC7/pVjKeQw+9NBDWrJkiWJiYlShQgX5+vrKx8fH+fyzzz6rJUuWaOXKlXrvvff03HPPad++fZL+Nwzm0n+NGjVyvvbNN9/UZ599pgkTJuj48eMKCQmRzWaTm5ub8wx1bnL7/rnSOl36misdC5mZmc7na9eurWXLluk///mP7rjjDsXHxyssLMz5ic6lJk6cqNWrV+vhhx9WUlKSHnzwQa1cufKqdaP40B8LDz3SNdAjrx398YLi6I+EwRvUrFkz/fzzzzLGZJs+e/ZsnT9/XomJic6Pdy/64Ycfso2T79Wrl5YtW6Y1a9bI398/xzd7bo4cOaLU1FTdcsstuc5z+vRpBQUF6bPPPtPChQtVpkwZ50XcJdml37RffPGFZs6cqSpVqjifL1++vKZNm6aJEyfq5MmT17TMypUr5/gGOnr0aI4hBp06ddKKFSu0atUqdezYMdtzzZs31w8//JBj2d9//32Oax+8vb01ZswYjR07NscxcFFcXJy+//57dejQQd26dZObm1uJ/mF9Je3atcs2FOaOO+64puP+onr16mnEiBEaNWqUUlNTsz13tX3x9ddfKzU1VYMHD1aHDh0UFxentWvX6tChQwW8hgWnUqVKOY7BY8eOXXGYi7e3t6ZMmaJJkyY5m9nlWrZsqVtuuUU//fRTvuoIDg7WPffco4iICElS/fr1df78eSUlJWWb7/PPP9e7774r6cL3z+X75+jRo6pUqVKu79O8eXPt3r07x/fo999/rzp16qhy5cqaPXu2Dh8+rObNm+upp55SXFycfHx8sp1Jl6Q1a9Zo+fLlql69unr16qU5c+Zkux4EJQ/9sfDQI10HPfLa0B8vKI7+SBi8Qa1atVK1atU0b948Z8L/5ptvFBcXpz59+ui2227TtGnTnN/0iYmJWrBggZ5++mnnMoKDg7Vx40YtW7ZMvXr1uqb3TU9P16xZs9SjR4+rXky9f/9+Pf3008rMzFRqaqpiY2NzDCNwVReHwlxrY7jrrru0Zs0aHTt2TNKFMeHLly933r3rosaNG+vIkSOKiYlRSEhItufCw8O1devWbBchx8fHa9u2bXr44YdzvGe3bt1Up06dbOP6L0pMTNShQ4e0Zs0arV69WqtXr9Ybb7yhzz77zHkG0VVcHApz+PBh1ahR45qO+0t17dpVtWrVynG9xNX2RVxcnJ577jnntvvmm2/k5+fnvJC8JPL19dX27du1d+9eSRe+jz/99NMcx+BFLVu21L333uu8CcblDhw4oP3796tx48b5ruW5557T1q1btWbNGpUrV059+/bViy++6Dz29u/fr9mzZzvvvtamTRstXrzY+Yv9pk2bdPbs2Rx3Z7vU3/72N4WGhmrcuHE6c+aMJGnv3r2aPn26Bg8eLOnChe+vvfaa89qhlJQUHTt2LMeQvnLlyunll1/W/v37JV0467pz5041adIk3+uOokF/LF70yJKDHpk3+mPx9UfuJnqDbDab5s+fr+nTp6tr166y2+2qWrWq3nzzTd18882aN2+e5syZo65du8rd3V2VK1fWSy+9lO1OXuXKlVPbtm313XffqXXr1rm+V2JiosLCwiRJWVlZatOmjUaNGnXV+ho3bqygoCB169ZNWVlZevTRR+Xn51cwK18CDB8+XGvXrs02LTIyMscY7IULF6phw4YaOHCgHn30UUkXtuEDDzygwMDAHMvt2LGjNm3apBo1aji/uSSpatWq+uCDDzRr1iwtWLBAxhg1aNBAixYtct4l7XITJ050DtO4VFxcnHr27Kly5co5p911112qW7euPvvssys2zpLq4lCYf/7zn5J0Tcf95UaNGqVHH31U4eHh2aZfaV8cOXJE3333XbZrBSTpscce04svvqiwsDAlJSWpRYsWzuf8/Pz01ltvFdQqXxcvLy9NnjxZQ4cOVVZWltLT0xUUFKQ+ffrk+prhw4erc+fO2rJli6QL10S8++67cnd3V1pamkaPHq3/+7//0/79+51Dxy7VunVrRUZG5lhutWrVNGDAAM2aNUvt2rXTsGHD9Nprr+nBBx+U3W6Xu7u7nn/+ebVr107ShVuWT506VV27dpXNZlPlypU1f/58541BctveEyZM0BtvvKHevXvL3d1dZcqU0XPPPee8dfb48eM1c+ZMhYSEqHz58vLw8NCIESNyNNE2bdpo8ODBeuqpp5y/QN1zzz165pln8rsbUEToj8WPHlky0CPzRn8svv5oM5eP3wAAAAAAlHoMEwUAAAAACyIMAgAAAIAFEQYBAAAAwIIIgwAAAABgQYRBAAAAALAgwiCgC38zpkmTJgoLC3P+69at2zX9wc4xY8bo7bffLoIqC1fXrl313XffKTk5WQ899FBxlwMAKCHokfRIlF78nUHg/ytXrly2P5SbnJysrl27qlmzZtf1R0tdVfXq1a/5jxQDAKyBHnkBPRKlDWEQyEX16tV16623avfu3fr555+1YsUKvfHGG5Iu/DHcSx9fdPvtt+uxxx7T+vXrdfbsWQ0ePFgJCQn69ddf5ePjo9dff1033XSTtmzZolmzZuncuXPy8PDQ0KFDFRAQoLi4OK1atUpubm7as2ePypUrp5kzZ6p+/fr64Ycf9NJLLyk9PV0pKSlq27atpk2bpv3796tv376qX7++Dhw4oO7du+v333/Xyy+/LEnasmWLpkyZovj4+Gy1/v7774qIiNC5c+dUr149nT17VtKFM8ChoaH6/vvv9ccff2jcuHFKT0+XMUa9e/dW3759JUkLFizQypUr5XA4VKtWLU2YMEHVq1fPtc7MzExNnjxZ27Ztk4eHh2rXrq3p06erQoUK2rZtm6KionTu3Dm5ublp8ODBat++fSHvYQDA9aJH0iNRShgAZt++fcbX1zfbtG3btpnWrVubpKQks3jxYvPkk086n7v08ejRo81bb71ljDGmYcOG5t133zXGGPPGG2+YFi1amEOHDpmsrCzTo0cPs3TpUnPs2DHj7+9vfvjhB2OMMb/++qu58847zd69e83ixYuNn5+fOXjwoDHGmEmTJplRo0YZY4wZNmyY2bhxozHGmNOnT5u77rrL7Nixw+zbt880bNjQbN682RhjzJEjR0zLli3N8ePHjTHGjBw50ixatCjHOoeFhZmYmBhjjDFbtmwxjRo1Mhs3bsy2LcaOHWveeOMNY4wxhw8fNkOHDjVZWVnm008/NUOHDjUZGRnGGGM++ugj88QTT1y1zs2bN5uQkBDjcDiMMcbMmjXLbN261Zw4ccIEBQWZffv2GWOMOXTokAkICDAHDhzI1z4EABQOeiQ9EqUXnwwC/9/58+cVFhYmScrKylLVqlX10ksvqWbNmvlaTnBwsCTplltuUcOGDVW9enVJUu3atXXy5Elt375dt9xyi+644w5JUoMGDdSyZUtt2rRJNptNTZs2VY0aNSRJf//737Vq1SpJ0owZM/Tf//5Xr7/+uv7880+lpaXp7NmzqlKliux2u3x9fSVJ1apV07333qslS5aoe/fuWrdunSZMmJCtxuPHj2vXrl3q3r27JMnPz08NGjTIsS4dO3bU6NGjtX37dvn7+ysyMlJubm76+uuvtWPHDvXq1UuS5HA4dO7cuavW2bhxY7m7u+uBBx5Qu3btFBwcrObNm2vt2rVKSUnRM88843xfm82mXbt26W9/+1u+tj0AoHDQI+mRKJ0Ig8D/d/n1EJey2WwyxjgfZ2Rk5LocDw+PK359UVZWlmw2W7ZpxhhlZmbKw8ND5cqVu+L7PvLII2rUqJHuuecederUST/++KPzuTJlyshu/9+3c9++ffXiiy/KbrcrKChIFSpUuGKtl67Tpa+/qH379lqxYoXWr1+vDRs26LXXXlNcXJwcDoeeeOIJhYeHS5LS09N18uTJq9ZZqVIlLVmyRNu2bdPGjRs1dOhQ/fOf/1TNmjVVv359ffLJJ873TU5OlpeXVy5bGABQ1OiR9EiUTtxNFLgGXl5e+u2335SWlqaMjAytWLHiupfl6+urP//8U9u3b5ck/fbbb9q8ebPuvPPOXF9z6tQp7dixQyNGjFBQUJAOHTqkvXv3yuFwXHH+li1bys3NTW+//fYV73pWtWpVNW3a1NlcfvrpJ/3666855nv++ee1fPlydenSRRMmTJCnp6f27t2rdu3aKTY2VqdPn5YkzZ07V6NGjbpqnV9//bUeffRRtWjRQkOGDFH37t2VmJgoX19f7dmzR5s3b5Yk7dy5U8HBwUpOTs7fhgUAFAt6JD0SrotPBoFrcPfdd6t169bq1KmTvL29ddddd2nXrl3XtSwvLy/NnTtXkydP1vnz52Wz2TR9+nTVrVtX33///RVfU6lSJT355JPq0aOHbrrpJlWvXl0tW7bUnj17VKdOnSu+pmfPnlq+fHmud3mbPXu2xo4dq48++ki33HKL6tWrl2Oep59+WuPGjdPHH38sd3d33X///WrdurVatWql5ORkPfjgg7LZbKpZs6ZmzJhx1TofeOAB/fe//1XXrl110003qXLlypo8ebK8vLwUHR2tWbNmKS0tTcYYzZo1S7Vr176u7QsAKFr0SHokXJfNXPoZOIBSITMzU4MHD1a3bt3UuXPn4i4HAIASgx4J/A/DRIFS5vfff5e/v7+qVq2qkJCQ4i4HAIASgx4JZMcngwAAAABgQXwyCAAAAAAWRBgEAAAAAAsiDAIAAACABREGAQAAAMCCCIMAAAAAYEH/DyRoW0r+7fwgAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 1080x576 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# create bar plots with the number of training and testing\n",
    "# images in each folder per pulmonary disease\n",
    "figure, ax = plt.subplots(1,2, figsize = (15,8))\n",
    "\n",
    "sns.set_palette(\"Set2\")\n",
    "\n",
    "sns.barplot(x = 'class',y = 'count',data = quantity_train,ax = ax[0])\n",
    "sns.barplot(x = 'class',y = 'count',data = quantity_test,ax = ax[1])\n",
    "\n",
    "\n",
    "# set titles and labels\n",
    "ax[0].set_title('Number of training images per pulmonary disease')\n",
    "ax[0].set(xlabel = 'Pulmonary disease', ylabel = 'Number of images')\n",
    "\n",
    "ax[1].set_title('Number of testing images per pulmonary disease')\n",
    "ax[1].set(xlabel = 'Pulmonary disease', ylabel = 'Number of images')\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "97317844",
   "metadata": {},
   "source": [
    "## 4. Data preprocessing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dc2dda66",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: keras in ./opt/anaconda3/lib/python3.8/site-packages (2.9.0)\n",
      "Requirement already satisfied: tensorflow in ./opt/anaconda3/lib/python3.8/site-packages (2.9.0)\n",
      "Requirement already satisfied: keras-preprocessing>=1.1.1 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.1.2)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (3.7.4.3)\n",
      "Requirement already satisfied: six>=1.12.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.15.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.2.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.0.0)\n",
      "Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.9.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (14.0.1)\n",
      "Requirement already satisfied: tensorboard<2.10,>=2.9 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.9.0)\n",
      "Requirement already satisfied: protobuf>=3.9.2 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (3.20.1)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.12.1)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.46.1)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (3.3.0)\n",
      "Requirement already satisfied: flatbuffers<2,>=1.12 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.12)\n",
      "Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.9.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.6.3)\n",
      "Requirement already satisfied: packaging in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (20.9)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.1.0)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.4.0)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.26.0)\n",
      "Requirement already satisfied: numpy>=1.20 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.20.1)\n",
      "Requirement already satisfied: h5py>=2.9.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.10.0)\n",
      "Requirement already satisfied: setuptools in ./opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (52.0.0.post20210125)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in ./opt/anaconda3/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow) (0.36.2)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (0.4.6)\n",
      "Requirement already satisfied: markdown>=2.6.8 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (3.3.7)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.25.1)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.6.6)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (1.0.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (1.8.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./opt/anaconda3/lib/python3.8/site-packages (from tensorboard<2.10,>=2.9->tensorflow) (0.6.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (5.1.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in ./opt/anaconda3/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (4.8)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (0.2.8)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./opt/anaconda3/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow) (1.3.1)\n",
      "Requirement already satisfied: importlib-metadata>=4.4 in ./opt/anaconda3/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (4.11.3)\n",
      "Requirement already satisfied: zipp>=0.5 in ./opt/anaconda3/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (3.4.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./opt/anaconda3/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (0.4.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2020.12.5)\n",
      "Requirement already satisfied: idna<3,>=2.5 in ./opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2.10)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (1.26.4)\n",
      "Requirement already satisfied: chardet<5,>=3.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (4.0.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow) (3.2.0)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from packaging->tensorflow) (2.4.7)\n"
     ]
    }
   ],
   "source": [
    "!pip install keras\n",
    "!pip install tensorflow"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "49251865",
   "metadata": {},
   "source": [
    "rescale: rescales images by the given factor\n",
    "horizontal flip: randomly flip images horizontally.\n",
    "validation_split: percentage of images reserved for validation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "00f0583f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 6326 images belonging to 4 classes.\n",
      "Found 38 images belonging to 4 classes.\n",
      "Found 771 images belonging to 4 classes.\n"
     ]
    }
   ],
   "source": [
    "# use tensorflow for the data augmentation and preprocessing\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "# use ImageDataGenerator to rescale and horizontally flip the images\n",
    "train_image_gen = ImageDataGenerator(rescale=1./255, \n",
    "                                     horizontal_flip = True, \n",
    "                                     validation_split=0.2)\n",
    "\n",
    "test_image_gen  = ImageDataGenerator(rescale=1./255)\n",
    "\n",
    "valid_image_gen = ImageDataGenerator(rescale=1./255)\n",
    "\n",
    "\n",
    "\n",
    "# transform the images from RGB to grayscale - is going to speed up model training later\n",
    "# image size = 331 -> because of the pre trained model we're going to use\n",
    "# flow training images in batches of 20 using train_datagen generator\n",
    "train_generator = train_image_gen.flow_from_directory(directory=train_folders, \n",
    "                                                    target_size=(224, 224),\n",
    "                                                    color_mode=\"grayscale\",\n",
    "                                                    batch_size=32,\n",
    "                                                    class_mode=\"categorical\",\n",
    "                                                    shuffle=True,seed=42)\n",
    "\n",
    "\n",
    "valid_generator = valid_image_gen.flow_from_directory(directory=val_folders, \n",
    "                                                    target_size=(224, 224),\n",
    "                                                    color_mode=\"grayscale\",\n",
    "                                                    batch_size=32,\n",
    "                                                    class_mode=\"categorical\",\n",
    "                                                    shuffle=True,seed=42)\n",
    "\n",
    "test_generator = test_image_gen.flow_from_directory(directory=test_folders,\n",
    "                                                  target_size=(224, 224),\n",
    "                                                  color_mode=\"grayscale\",\n",
    "                                                  batch_size=1,\n",
    "                                                  class_mode=None,\n",
    "                                                  shuffle=False,\n",
    "                                                  seed=42)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0aac51da",
   "metadata": {},
   "source": [
    "## 5. Building the model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7816c1d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " conv2d (Conv2D)             (None, 220, 220, 128)     3328      \n",
      "                                                                 \n",
      " max_pooling2d (MaxPooling2D  (None, 73, 73, 128)      0         \n",
      " )                                                               \n",
      "                                                                 \n",
      " conv2d_1 (Conv2D)           (None, 69, 69, 64)        204864    \n",
      "                                                                 \n",
      " max_pooling2d_1 (MaxPooling  (None, 23, 23, 64)       0         \n",
      " 2D)                                                             \n",
      "                                                                 \n",
      " conv2d_2 (Conv2D)           (None, 21, 21, 30)        17310     \n",
      "                                                                 \n",
      " max_pooling2d_2 (MaxPooling  (None, 10, 10, 30)       0         \n",
      " 2D)                                                             \n",
      "                                                                 \n",
      " conv2d_3 (Conv2D)           (None, 8, 8, 30)          8130      \n",
      "                                                                 \n",
      " max_pooling2d_3 (MaxPooling  (None, 4, 4, 30)         0         \n",
      " 2D)                                                             \n",
      "                                                                 \n",
      " flatten (Flatten)           (None, 480)               0         \n",
      "                                                                 \n",
      " dense (Dense)               (None, 2048)              985088    \n",
      "                                                                 \n",
      " dense_1 (Dense)             (None, 512)               1049088   \n",
      "                                                                 \n",
      " dropout (Dropout)           (None, 512)               0         \n",
      "                                                                 \n",
      " dense_2 (Dense)             (None, 256)               131328    \n",
      "                                                                 \n",
      " dense_3 (Dense)             (None, 64)                16448     \n",
      "                                                                 \n",
      " dropout_1 (Dropout)         (None, 64)                0         \n",
      "                                                                 \n",
      " dense_4 (Dense)             (None, 32)                2080      \n",
      "                                                                 \n",
      " dense_5 (Dense)             (None, 4)                 132       \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 2,417,796\n",
      "Trainable params: 2,417,796\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout, BatchNormalization\n",
    "from tensorflow.keras.callbacks import EarlyStopping\n",
    "\n",
    "# creating the model\n",
    "model= Sequential()\n",
    "\n",
    "model.add(Conv2D(filters=128,strides= 1, kernel_size = (5,5), activation='relu', input_shape=(224,224,1,)))\n",
    "model.add(MaxPool2D(3,3))\n",
    "model.add(Conv2D(filters=64,kernel_size = (5,5),activation='relu'))\n",
    "model.add(MaxPool2D(3,3))\n",
    "\n",
    "model.add(Conv2D(filters=30,kernel_size = (3,3),activation='relu'))\n",
    "model.add(MaxPool2D(2,2))\n",
    "model.add(Conv2D(filters=30,kernel_size = (3,3),activation='relu'))\n",
    "model.add(MaxPool2D(2,2))\n",
    "\n",
    "model.add(Flatten())\n",
    "model.add(Dense(2048,activation='relu'))\n",
    "model.add(Dense(512,activation='relu'))\n",
    "model.add(Dropout(.1))\n",
    "model.add(Dense(256,activation='relu'))\n",
    "model.add(Dense(64,activation='relu'))\n",
    "model.add(Dropout(.1))\n",
    "model.add(Dense(32,activation='relu'))\n",
    "model.add(Dense(4,activation = 'softmax'))\n",
    "model.compile(loss = 'categorical_crossentropy', optimizer ='adam', metrics= ['accuracy'])\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a42b3d96",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/15\n",
      "197/197 [==============================] - 719s 4s/step - loss: 0.7272 - accuracy: 0.7129 - val_loss: 0.8589 - val_accuracy: 0.6250\n",
      "Epoch 2/15\n",
      "197/197 [==============================] - 666s 3s/step - loss: 0.3646 - accuracy: 0.8642 - val_loss: 0.6535 - val_accuracy: 0.7188\n",
      "Epoch 3/15\n",
      "197/197 [==============================] - 671s 3s/step - loss: 0.2731 - accuracy: 0.9021 - val_loss: 0.5306 - val_accuracy: 0.7188\n",
      "Epoch 4/15\n",
      "197/197 [==============================] - 633s 3s/step - loss: 0.2653 - accuracy: 0.9082 - val_loss: 0.6662 - val_accuracy: 0.7812\n",
      "Epoch 5/15\n",
      "197/197 [==============================] - 634s 3s/step - loss: 0.2152 - accuracy: 0.9263 - val_loss: 0.6274 - val_accuracy: 0.7188\n",
      "Epoch 6/15\n",
      "197/197 [==============================] - 636s 3s/step - loss: 0.1827 - accuracy: 0.9390 - val_loss: 0.5367 - val_accuracy: 0.8125\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<keras.callbacks.History at 0x7fc4a2ee5580>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# hyperparameters\n",
    "STEP_SIZE_TRAIN = train_generator.n//train_generator.batch_size\n",
    "STEP_SIZE_VALID = valid_generator.n//valid_generator.batch_size\n",
    "\n",
    "# stop the training when there is no improvement after 3 epochs\n",
    "early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n",
    "\n",
    "# fit the model\n",
    "model.fit(train_generator,steps_per_epoch=STEP_SIZE_TRAIN,\n",
    "          validation_data=valid_generator,verbose= 1,\n",
    "          validation_steps=STEP_SIZE_VALID,\n",
    "          epochs=15, callbacks=early_stop)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b66d3ce1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1/1 [==============================] - 1s 1s/step - loss: 0.5180 - accuracy: 0.7500\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[0.5180084705352783, 0.75]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# evaluate the model\n",
    "model.evaluate(valid_generator,steps=STEP_SIZE_VALID)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "ac541ed2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# save the model\n",
    "model.save(\"ChestXrayModel.h5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ffb78d9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c05c7a0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "eef4096b",
   "metadata": {},
   "source": [
    "## 6. Using a pre-trained model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "055f5bad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"model\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " input_8 (InputLayer)        [(None, 150, 150, 3)]     0         \n",
      "                                                                 \n",
      " sequential_3 (Sequential)   (None, 150, 150, 3)       0         \n",
      "                                                                 \n",
      " rescaling (Rescaling)       (None, 150, 150, 3)       0         \n",
      "                                                                 \n",
      " xception (Functional)       (None, 5, 5, 2048)        20861480  \n",
      "                                                                 \n",
      " global_average_pooling2d_2   (None, 2048)             0         \n",
      " (GlobalAveragePooling2D)                                        \n",
      "                                                                 \n",
      " dropout_4 (Dropout)         (None, 2048)              0         \n",
      "                                                                 \n",
      " dense_14 (Dense)            (None, 1)                 2049      \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 20,863,529\n",
      "Trainable params: 2,049\n",
      "Non-trainable params: 20,861,480\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from tensorflow import keras\n",
    "from tensorflow.keras import layers\n",
    "\n",
    "data_augmentation = keras.Sequential(\n",
    "    [layers.RandomFlip(\"horizontal\"), layers.RandomRotation(0.1),]\n",
    ")\n",
    "\n",
    "# first pretrained model using Xception\n",
    "base_pt_model = keras.applications.Xception(\n",
    "    weights=\"imagenet\",  # Load weights pre-trained on ImageNet.\n",
    "    input_shape=(150, 150, 3),\n",
    "    include_top=False,\n",
    ")  # Do not include the ImageNet classifier at the top.\n",
    "\n",
    "# Freeze the base_model\n",
    "base_pt_model.trainable = False\n",
    "\n",
    "# Create new model on top\n",
    "inputs = keras.Input(shape=(150, 150, 3))\n",
    "x = data_augmentation(inputs)  # Apply random data augmentation\n",
    "\n",
    "# Pre-trained Xception weights requires that input be scaled\n",
    "# from (0, 255) to a range of (-1., +1.), the rescaling layer\n",
    "# outputs: `(inputs * scale) + offset`\n",
    "scale_layer = keras.layers.Rescaling(scale=1 / 127.5, offset=-1)\n",
    "x = scale_layer(x)\n",
    "\n",
    "# The base model contains batchnorm layers. We want to keep them in inference mode\n",
    "# when we unfreeze the base model for fine-tuning, so we make sure that the\n",
    "# base_model is running in inference mode here.\n",
    "x = base_pt_model(x, training=False)\n",
    "x = keras.layers.GlobalAveragePooling2D()(x)\n",
    "x = keras.layers.Dropout(0.2)(x)  # Regularize with dropout\n",
    "outputs = keras.layers.Dense(1)(x)\n",
    "pt_model = keras.Model(inputs, outputs)\n",
    "\n",
    "pt_model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "32090bd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'model/sequential_3/random_flip/map/TensorArrayUnstack/TensorListFromTensor' defined at (most recent call last):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-32-213a4af9d1e7>\", line 9, in <module>\n      pt_model.fit(train_generator, epochs=epochs, validation_data=valid_generator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1409, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1051, in train_function\n      return step_function(self, iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1040, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1030, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 889, in train_step\n      y_pred = self(x, training=True)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/preprocessing/image_preprocessing.py\", line 390, in call\n      return self._format_output(self._batch_augment(inputs), is_dict)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/preprocessing/image_preprocessing.py\", line 416, in _batch_augment\n      return self._map_fn(self._augment, inputs)\nNode: 'model/sequential_3/random_flip/map/TensorArrayUnstack/TensorListFromTensor'\nSpecified a list with shape [150,150,3] from a tensor with shape [224,224,1]\n\t [[{{node model/sequential_3/random_flip/map/TensorArrayUnstack/TensorListFromTensor}}]] [Op:__inference_train_function_95535]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-32-213a4af9d1e7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0mepochs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m20\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 9\u001b[0;31m \u001b[0mpt_model\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrain_generator\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mepochs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalidation_data\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mvalid_generator\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     52\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     55\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'model/sequential_3/random_flip/map/TensorArrayUnstack/TensorListFromTensor' defined at (most recent call last):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-32-213a4af9d1e7>\", line 9, in <module>\n      pt_model.fit(train_generator, epochs=epochs, validation_data=valid_generator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1409, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1051, in train_function\n      return step_function(self, iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1040, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1030, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 889, in train_step\n      y_pred = self(x, training=True)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/preprocessing/image_preprocessing.py\", line 390, in call\n      return self._format_output(self._batch_augment(inputs), is_dict)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/preprocessing/image_preprocessing.py\", line 416, in _batch_augment\n      return self._map_fn(self._augment, inputs)\nNode: 'model/sequential_3/random_flip/map/TensorArrayUnstack/TensorListFromTensor'\nSpecified a list with shape [150,150,3] from a tensor with shape [224,224,1]\n\t [[{{node model/sequential_3/random_flip/map/TensorArrayUnstack/TensorListFromTensor}}]] [Op:__inference_train_function_95535]"
     ]
    }
   ],
   "source": [
    "# train the top layer\n",
    "pt_model.compile(\n",
    "    optimizer=keras.optimizers.Adam(),\n",
    "    loss=keras.losses.BinaryCrossentropy(from_logits=True),\n",
    "    metrics=[keras.metrics.BinaryAccuracy()],\n",
    ")\n",
    "\n",
    "epochs = 20\n",
    "pt_model.fit(train_generator, epochs=epochs, validation_data=valid_generator)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "564e5b78",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d5a988c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c187ee6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "83d6f8b3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "84b75a96",
   "metadata": {},
   "outputs": [],
   "source": [
    "# second pretrained model using InceptionResNetV2\n",
    "# load the InceptionResNetV2 architecture with imagenet weights as base\n",
    "base_model = tf.keras.applications.InceptionResNetV2(\n",
    "                     include_top=False,\n",
    "                     weights='imagenet',\n",
    "                     input_shape=(331,331,3)\n",
    "                     )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "828c4e58",
   "metadata": {},
   "outputs": [],
   "source": [
    "# freeze the layer so that the base_model's internal state will not change during training\n",
    "base_model.trainable=False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "2b147c7c",
   "metadata": {},
   "outputs": [],
   "source": [
    "pt_model = tf.keras.Sequential([\n",
    "        base_model,  \n",
    "        tf.keras.layers.BatchNormalization(renorm=True), #speeds up training\n",
    "        tf.keras.layers.GlobalAveragePooling2D(),\n",
    "        tf.keras.layers.Dense(512, activation='relu'),\n",
    "        tf.keras.layers.Dense(256, activation='relu'),\n",
    "        tf.keras.layers.Dropout(0.5),\n",
    "        tf.keras.layers.Dense(128, activation='relu'),\n",
    "        tf.keras.layers.Dense(120, activation='softmax')\n",
    "    ])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "9b891f6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# compile the model\n",
    "pt_model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "e4c37852",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_2\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " inception_resnet_v2 (Functi  (None, 9, 9, 1536)       54336736  \n",
      " onal)                                                           \n",
      "                                                                 \n",
      " batch_normalization_411 (Ba  (None, 9, 9, 1536)       10752     \n",
      " tchNormalization)                                               \n",
      "                                                                 \n",
      " global_average_pooling2d_1   (None, 1536)             0         \n",
      " (GlobalAveragePooling2D)                                        \n",
      "                                                                 \n",
      " dense_10 (Dense)            (None, 512)               786944    \n",
      "                                                                 \n",
      " dense_11 (Dense)            (None, 256)               131328    \n",
      "                                                                 \n",
      " dropout_3 (Dropout)         (None, 256)               0         \n",
      "                                                                 \n",
      " dense_12 (Dense)            (None, 128)               32896     \n",
      "                                                                 \n",
      " dense_13 (Dense)            (None, 120)               15480     \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 55,314,136\n",
      "Trainable params: 969,720\n",
      "Non-trainable params: 54,344,416\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "# print the summary of the model\n",
    "pt_model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "c009d1e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# early stopping call back\n",
    "early = tf.keras.callbacks.EarlyStopping( patience=10,\n",
    "                                          min_delta=0.001,\n",
    "                                          restore_best_weights=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "9da615eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/15\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'sequential_2/inception_resnet_v2/activation_203/Relu' defined at (most recent call last):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-28-e40d2e632c73>\", line 2, in <module>\n      pt_model.fit(train_generator,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1409, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1051, in train_function\n      return step_function(self, iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1040, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1030, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 889, in train_step\n      y_pred = self(x, training=True)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/activation.py\", line 57, in call\n      return self.activation(inputs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/activations.py\", line 311, in relu\n      return backend.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/backend.py\", line 4992, in relu\n      x = tf.nn.relu(x)\nNode: 'sequential_2/inception_resnet_v2/activation_203/Relu'\ninput depth must be evenly divisible by filter depth: 1 vs 3\n\t [[{{node sequential_2/inception_resnet_v2/activation_203/Relu}}]] [Op:__inference_train_function_84140]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-28-e40d2e632c73>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# fit model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m pt_model.fit(train_generator, \n\u001b[0m\u001b[1;32m      3\u001b[0m              \u001b[0msteps_per_epoch\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mSTEP_SIZE_TRAIN\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m              \u001b[0mvalidation_data\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mvalid_generator\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m              \u001b[0mvalidation_steps\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mSTEP_SIZE_VALID\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     52\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     55\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'sequential_2/inception_resnet_v2/activation_203/Relu' defined at (most recent call last):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-28-e40d2e632c73>\", line 2, in <module>\n      pt_model.fit(train_generator,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1409, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1051, in train_function\n      return step_function(self, iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1040, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1030, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 889, in train_step\n      y_pred = self(x, training=True)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/activation.py\", line 57, in call\n      return self.activation(inputs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/activations.py\", line 311, in relu\n      return backend.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/backend.py\", line 4992, in relu\n      x = tf.nn.relu(x)\nNode: 'sequential_2/inception_resnet_v2/activation_203/Relu'\ninput depth must be evenly divisible by filter depth: 1 vs 3\n\t [[{{node sequential_2/inception_resnet_v2/activation_203/Relu}}]] [Op:__inference_train_function_84140]"
     ]
    }
   ],
   "source": [
    "# fit model\n",
    "pt_model.fit(train_generator, \n",
    "             steps_per_epoch=STEP_SIZE_TRAIN, \n",
    "             validation_data=valid_generator, \n",
    "             validation_steps=STEP_SIZE_VALID, \n",
    "             epochs=15, \n",
    "             callbacks=[early])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "917e22a1",
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'sequential_1/inception_resnet_v2/activation/Relu' defined at (most recent call last):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-19-7a89e592e2da>\", line 2, in <module>\n      pt_model.evaluate(valid_generator,steps=STEP_SIZE_VALID)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1756, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1557, in test_function\n      return step_function(self, iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1546, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1535, in run_step\n      outputs = model.test_step(data)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1499, in test_step\n      y_pred = self(x, training=False)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/activation.py\", line 57, in call\n      return self.activation(inputs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/activations.py\", line 311, in relu\n      return backend.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/backend.py\", line 4992, in relu\n      x = tf.nn.relu(x)\nNode: 'sequential_1/inception_resnet_v2/activation/Relu'\ninput depth must be evenly divisible by filter depth: 1 vs 3\n\t [[{{node sequential_1/inception_resnet_v2/activation/Relu}}]] [Op:__inference_test_function_47251]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-19-7a89e592e2da>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# evaluate the model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mpt_model\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mevaluate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvalid_generator\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0msteps\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mSTEP_SIZE_VALID\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     52\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     55\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'sequential_1/inception_resnet_v2/activation/Relu' defined at (most recent call last):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n      app.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 612, in start\n      self.io_loop.start()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n      lambda f: self._run_callback(functools.partial(callback, future))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n      ret = callback()\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 814, in inner\n      self.ctx_run(self.run)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 775, in run\n      yielded = self.gen.send(value)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 365, in process_one\n      yield gen.maybe_future(dispatch(*args))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n      yield gen.maybe_future(handler(stream, idents, msg))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 543, in execute_request\n      self.do_execute(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\n      yielded = ctx_run(next, result)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 306, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2894, in run_cell\n      result = self._run_cell(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n      return runner(coro)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"<ipython-input-19-7a89e592e2da>\", line 2, in <module>\n      pt_model.evaluate(valid_generator,steps=STEP_SIZE_VALID)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1756, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1557, in test_function\n      return step_function(self, iterator)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1546, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1535, in run_step\n      outputs = model.test_step(data)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 1499, in test_step\n      y_pred = self(x, training=False)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py\", line 490, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 458, in call\n      return self._run_internal_graph(\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/layers/core/activation.py\", line 57, in call\n      return self.activation(inputs)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/activations.py\", line 311, in relu\n      return backend.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)\n    File \"/Users/mardjabueno/opt/anaconda3/lib/python3.8/site-packages/keras/backend.py\", line 4992, in relu\n      x = tf.nn.relu(x)\nNode: 'sequential_1/inception_resnet_v2/activation/Relu'\ninput depth must be evenly divisible by filter depth: 1 vs 3\n\t [[{{node sequential_1/inception_resnet_v2/activation/Relu}}]] [Op:__inference_test_function_47251]"
     ]
    }
   ],
   "source": [
    "# evaluate the model\n",
    "pt_model.evaluate(valid_generator,steps=STEP_SIZE_VALID)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0d4d42f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# save the model\n",
    "pt_model.save(\"ChestXrayModel_pretrained.h5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3777576c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
